# Shell variables
# Generated by 'wal'
wallpaper='/home/salil/Pictures/wallpapers/japan_shop.jpg'

# Special
background='#10100c'
foreground='#c7c6c3'
cursor='#c7c6c3'

# Colors
color0='#10100c'
color1='#8B7462'
color2='#67912D'
color3='#6C915C'
color4='#949969'
color5='#A8C357'
color6='#6D8A91'
color7='#c7c6c3'
color8='#8b8a88'
color9='#8B7462'
color10='#67912D'
color11='#6C915C'
color12='#949969'
color13='#A8C357'
color14='#6D8A91'
color15='#c7c6c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
