--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/salil/Pictures/wallpapers/japan_shop.jpg"

-- Special
background="#10100c"
foreground="#c7c6c3"
cursor="#c7c6c3"

-- Colors
color0="#10100c"
color1="#8B7462"
color2="#67912D"
color3="#6C915C"
color4="#949969"
color5="#A8C357"
color6="#6D8A91"
color7="#c7c6c3"
color8="#8b8a88"
color9="#8B7462"
color10="#67912D"
color11="#6C915C"
color12="#949969"
color13="#A8C357"
color14="#6D8A91"
color15="#c7c6c3"
