alias cf='cd ~/.config'
alias cfb='cd ~/.config/bspwm'
alias cfs='cd ~/.config/sxhkd'
alias cfi='cd ~/.config/i3'
alias cfp='cd ~/.config/polybar'
alias ch='cd ~/'
alias cs='cd ~/.scripts'
alias cff='cd ~/.config/fish'
